### ISSUE TITLE
No GTK enabled python3

### ISSUE THREAD

**Issue by xpix** [raspberrypi/skygate#4]
Hello install normal via apt on stretch:

```
pi@XSkyGateway:~/skygate/skygate $ ./skygate-gateway
Traceback (most recent call last):
  File "skygate.py", line 4, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

pi@XSkyGateway:~/skygate/skygate $ python3 ./test_lora.py
Traceback (most recent call last):
  File "./test_lora.py", line 1, in <module>
    from skygate.lora import *
  File "/home/pi/skygate/skygate/skygate.py", line 4, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

pi@XSkyGateway:~ $ skygate
Traceback (most recent call last):
  File "/usr/bin/skygate", line 2, in <module>
    import skygate.skygate
  File "/usr/lib/python3/dist-packages/skygate/skygate.py", line 4, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

pi@XSkyGateway:~ $ sudo skygate
Traceback (most recent call last):
  File "/usr/bin/skygate", line 2, in <module>
    import skygate.skygate
  File "/usr/lib/python3/dist-packages/skygate/skygate.py", line 4, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

whats wrong?

**Comment by XECDesign** [comment]
What's the output of `apt policy python3-gi`?

**Comment by xpix** [comment]
```
pi@XSkyGateway:~ $ apt policy python3-gi
python3-gi:
  Installed: 3.22.0-2
  Candidate: 3.22.0-2
  Version table:
 *** 3.22.0-2 500
        500 http://mirrordirector.raspbian.org/raspbian stretch/main armhf
Packages
        100 /var/lib/dpkg/status
```
Am Mi., 8. Aug. 2018 um 15:23 Uhr schrieb XECDesign <
notifications@github.com>:

**Comment by xpix** [comment]
Hi some news about this topic? :)

**Comment by XECDesign** [comment]
Unfortunately not. The output of that command looks mostly like what I'd expect. There may be another missing dependency, but I am not a python expert.

@daveake, would you happen to know what would be causing that error?

**Comment by daveake** [comment]
Yes looks like a missing dependency; is this on full-fat Stretch (needs to
be) or Lite ?

**Comment by XECDesign** [comment]
Which specific file is it looking for in that case? Even if installed on lite, apt should pull in the required dependencies. If we can figure that out, I can fix the dependencies.

**Comment by daveake** [comment]
I believe it's gir1.2-gtk-3.0

Happy to run a Lite install and check but won't be till tomorrow.

Dave

**Comment by XECDesign** [comment]
Looks like you're right. I've just removed it from my system and am seeing the same error.

@xpix, if you run `sudo apt install gir1.2-gtk-3.0`, that should take care of the problem. I'll push out an update to make sure that happens automatically in the future.

**Comment by xpix** [comment]
Thats the solution:
sudo apt install gir1.2-gtk-3.0
